//
//  MovieListInterfaces.swift
//  movieApp
//
//  Created by Carlos Torres Sanchez on 6/26/19.
//  Copyright (c) 2019 Carlos Torres Sanchez. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol MovieListWireframeInterface: WireframeInterface {
}

protocol MovieListViewInterface:class {
  func showMovies(with movies:Movies)
  
}

protocol MovieListPresenterInterface:class {
  func requestMovies(with category:String)
}

protocol MovieListInteractorInterface:class{
  func requestMovies(with category:String)

}

protocol MovieListInteractorOutputDelegate:class{
  func onMoviesFetched(with movies:Movies)
}
