//
//  NewScreenInterfaces.swift
//  movieApp
//
//  Created by Carlos Torres Sanchez on 6/26/19.
//  Copyright (c) 2019 Carlos Torres Sanchez. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol NewScreenWireframeInterface: WireframeInterface {
}

protocol NewScreenViewInterface:class {
}

protocol NewScreenPresenterInterface:class {
}

protocol NewScreenInteractorInterface:class{
}
