//
//  NewScreenInterfaces.swift
//  movieApp
//
//  Created by Carlos Torres Sanchez on 6/26/19.
//  Copyright (c) 2019 Carlos Torres Sanchez. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol NewScreenWireframeInterface: WireframeInterface {
}

protocol NewScreenViewInterface:class {
  func showMovies(with movies:Movies)
  
}

protocol NewScreenPresenterInterface:class {
  func requestMovies(with category:String)
}

protocol NewScreenInteractorInterface:class{
  func requestMovies(with category:String)

}

protocol NewScreenInteractorOutputDelegate:class{
  func onMoviesFetched(with movies:Movies)
}
