//
//  NewScreenViewController.swift
//  movieApp
//
//  Created by Carlos Torres Sanchez on 6/26/19.
//  Copyright (c) 2019 Carlos Torres Sanchez. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class NewScreenViewController: UIViewController {

    // MARK: - Public properties -

  @IBOutlet var movieSelectorOptions: [UISegmentedControl]!
  @IBOutlet weak var moviesTable: UITableView!
  var movies:Movies?
  
  
  var presenter: NewScreenPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
          presenter.requestMovies(with: "Top Rated")
    }
	
}

// MARK: - Extensions -

extension NewScreenViewController: NewScreenViewInterface {
 
  func showMovies(with movies: Movies) {
    self.movies = movies
    moviesTable.delegate = self
    moviesTable.dataSource = self
    moviesTable.reloadData()
    
  }
  
}

extension NewScreenViewController:UITableViewDelegate{
  
  func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
    navigationController?.presentWireframe(MovieDetailWireframe(with: (movies?.results[indexPath.row])!))
  }
  
}


extension NewScreenViewController:UITableViewDataSource{
  func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
    return (movies?.results.count)!
  }
  
  func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    if let cell = tableView.dequeueReusableCell(withIdentifier: "movieCell", for: indexPath) as? MovieTableViewCell{
      
      cell.setMovieInCell(with: (movies?.results[indexPath.row])!)
      return cell
      
    }
    else{
      return UITableViewCell()
    }
  }
  
  
}
