//
//  NewScreenInteractor.swift
//  movieApp
//
//  Created by Carlos Torres Sanchez on 6/26/19.
//  Copyright (c) 2019 Carlos Torres Sanchez. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class NewScreenInteractor {
}

// MARK: - Extensions -

extension NewScreenInteractor: NewScreenInteractorInterface {
}
