//
//  MovieListInteractor.swift
//  movieApp
//
//  Created by Carlos Torres Sanchez on 6/26/19.
//  Copyright (c) 2019 Carlos Torres Sanchez. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MovieListInteractor {
  weak static var presenterDelegate:MovieListInteractorOutputDelegate?
}

// MARK: - Extensions -

extension MovieListInteractor: MovieListInteractorInterface {
  func requestMovies(with category: String) {
    
    let apiManager = ApiManager()
    apiManager.delegate  = self
    apiManager.getDataFromService(with: URL(string: "https://api.themoviedb.org/3/movie/\(category)?api_key=66393df0e6128ac9bcc5c318895c8f77")!, jsonInputString: "", contentType: "", contentTypeHeader: "", method: RemoteAPIConstants.httpMethodGet)
    
  }
  
}

extension MovieListInteractor:APIManagerDelegate{
  func onError(delegate: ApiManager) {
    
  }
  
  func onSucess(delegate: ApiManager, data: Data) {
    if let  movies = JSONParser<Movies>().parseJSONToObject(with: data){
      MovieListInteractor.presenterDelegate?.onMoviesFetched(with: movies)

    }
  }
  
  
}
