//
//  MovieListViewController.swift
//  movieApp
//
//  Created by Carlos Torres Sanchez on 6/26/19.
//  Copyright (c) 2019 Carlos Torres Sanchez. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MovieListViewController: UIViewController {

    // MARK: - Public properties -
  @IBOutlet weak var searchButton: UIBarButtonItem!
  @IBOutlet weak var searchBar: UISearchBar!
  @IBOutlet var movieSelectorOptions: [UISegmentedControl]!
  @IBOutlet weak var moviesTable: UITableView!
  var movies:Movies?
  var filteredMovies = [MovieResult]()
  var scopeTitles = ["Popular","Top Rated", "Upcoming"]
  var searchBarController:UISearchController?
  var isSearching = false
  
  
  var presenter: MovieListPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        self.title  = "Popular"
        presenter.requestMovies(with: "popular")
    }
  
  
  
  
  func isFiltering() ->Bool{
    print("Is filtering output")
    return searchBarController?.searchBar.text?.isEmpty == false && searchBarController?.isActive == true
  }
  
  
  @IBAction func searchMovies(_ sender: Any) {
    searchBarController = UISearchController(searchResultsController: nil)
    searchBarController?.hidesNavigationBarDuringPresentation = false
    searchBarController?.searchBar.placeholder = "Find Movies"
    searchBarController?.searchBar.scopeButtonTitles = scopeTitles
    searchBarController?.obscuresBackgroundDuringPresentation = false
    searchBarController?.searchBar.keyboardType = UIKeyboardType.asciiCapable
    searchBarController?.searchResultsUpdater = self
    self.searchBarController?.searchBar.delegate = self
    present(searchBarController!, animated: true, completion: nil)

  }
  
  @IBAction func refreshBtnPress(_ sender: Any) {
    self.title  = "Popular"
    presenter.requestMovies(with: "popular")
  }
  
  
  
  
  func filterContentForSearchText(_ searchText: String) {
  
    self.title = "Search Results"
    filteredMovies = (movies?.results.filter({( movie : MovieResult) -> Bool in
     return movie.title.lowercased().contains(searchText.lowercased())
   }))!
    moviesTable.reloadData()
    
  }
	
}

// MARK: - Extensions -

extension MovieListViewController: MovieListViewInterface {
 
  func showMovies(with movies: Movies) {
    self.movies = movies
    searchButton.isEnabled = true
    moviesTable.delegate = self
    moviesTable.dataSource = self
    moviesTable.reloadData()
    
  }
 
  
}

extension MovieListViewController:UITableViewDelegate{
  
  func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
    if isFiltering() {
      navigationController?.pushWireframe(MovieDetailWireframe(with: (filteredMovies[indexPath.row])))
      searchBarController?.dismiss(animated: true, completion: nil)

    }
    else{
      navigationController?.pushWireframe(MovieDetailWireframe(with: (movies?.results[indexPath.row])!))

    }
  }
  
}


extension MovieListViewController:UITableViewDataSource{
  func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
    
    if isFiltering(){
      return filteredMovies.count
    }
    else{
    return (movies?.results.count)!
    }
  }
  
  func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    if let cell = tableView.dequeueReusableCell(withIdentifier: "movieCell", for: indexPath) as? MovieTableViewCell{
      
      if isFiltering(){
        print(filteredMovies[indexPath.row])
        cell.setMovieInCell(with: (filteredMovies[indexPath.row]))
      }else{
      cell.setMovieInCell(with: (movies?.results[indexPath.row])!)
      }
      return cell
      
    }
    else{
      return UITableViewCell()
    }
  }
  
  
  
  
}


extension MovieListViewController:UISearchResultsUpdating{
  func updateSearchResults(for searchController: UISearchController) {
    self.filterContentForSearchText(searchController.searchBar.text!)
    
  }
  
  
}

extension MovieListViewController:UISearchBarDelegate{
  
 func searchBarCancelButtonClicked(_ searchBar: UISearchBar){
  searchBarController?.isActive = false
  searchBarController?.searchBar.text = ""
}
  
  func searchBar(_ searchBar: UISearchBar, selectedScopeButtonIndexDidChange selectedScope: Int) {
    presenter.requestMoviesByScopeIndex(index: selectedScope)
    
  }
  
  
}
