//
//  MovieDetailViewController.swift
//  movieApp
//
//  Created by Carlos Torres Sanchez on 7/1/19.
//  Copyright (c) 2019 Carlos Torres Sanchez. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MovieDetailViewController: UIViewController {

  @IBOutlet weak var movieImage: UIImageView!
  @IBOutlet weak var numberOfVotes: UILabel!
  @IBOutlet weak var movieOriginalTitle: UILabel!
  @IBOutlet weak var movieYear: UILabel!
  @IBOutlet weak var movieName: UILabel!
  @IBOutlet weak var synopsis: UITextView!

  var presenter: MovieDetailPresenterInterface!


  override func viewDidLoad() {
      super.viewDidLoad()
      movieImage.image = UIImage(named: "placeholderimage")
    presenter.presentMovie()
    }
	
  @IBAction func goBack(_ sender: Any) {
    self.dismiss(animated: true, completion: nil)
  }
  
}

// MARK: - Extensions -

extension MovieDetailViewController: MovieDetailViewInterface {
  func presentMovieCoverImage(Data: Data) {
     movieImage.image = UIImage(data: Data)
  }
  
  func presentMovieDetail(with movie: MovieResult) {
    movieName.text = movie.title
    movieYear.text = "Released: "+movie.release_date
    movieOriginalTitle.text = "Original Title: "+movie.original_title
    synopsis.text = movie.overview
    numberOfVotes.text = "Votes: " + movie.vote_count.description
    presenter.presentMovieCoverImage(URL:  URL(string:"https://image.tmdb.org/t/p/w500/"+movie.poster_path)!)
  }
  
  
  
}
extension MovieDetailViewController:DownloadManagerDelegate{
  func didDownloadImage(_: DownloadManager, data: Data) {
    
    movieImage.image = UIImage(data: data)
  }
  
  
  
}
