//
//  MovieDetailWireframe.swift
//  movieApp
//
//  Created by Carlos Torres Sanchez on 7/1/19.
//  Copyright (c) 2019 Carlos Torres Sanchez. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MovieDetailWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let storyboard = UIStoryboard(name: "MovieDetail", bundle: nil)

    // MARK: - Module setup -

  init(with movie:MovieResult) {
        let moduleViewController = storyboard.instantiateViewController(ofType: MovieDetailViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = MovieDetailInteractor()
        let presenter = MovieDetailPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
        interactor.presenter = presenter
        presenter.movie = movie
    }

}

// MARK: - Extensions -

extension MovieDetailWireframe: MovieDetailWireframeInterface {
}
