//
//  MovieDetailInteractor.swift
//  movieApp
//
//  Created by Carlos Torres Sanchez on 7/1/19.
//  Copyright (c) 2019 Carlos Torres Sanchez. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MovieDetailInteractor {
  var presenter:MovieDetailInteractorPresenterInterface?
}

// MARK: - Extensions -

extension MovieDetailInteractor: MovieDetailInteractorInterface {
 
  
  func presentMovieCoverImage(URL: URL) {
    let download = DownloadManager()
    download.delegate = self
    download.startDownload(from: URL)
  }
  
}
extension MovieDetailInteractor:DownloadManagerDelegate{
  func didDownloadImage(_: DownloadManager, data: Data) {
    presenter?.presentMovieCoverImage(data: data)
  }
  
  
}
