//
//  MovieDetailInterfaces.swift
//  movieApp
//
//  Created by Carlos Torres Sanchez on 7/1/19.
//  Copyright (c) 2019 Carlos Torres Sanchez. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol MovieDetailWireframeInterface: WireframeInterface {
}

protocol MovieDetailViewInterface:class {
  func presentMovieDetail(with movie:MovieResult)
}

protocol MovieDetailPresenterInterface:class{
  
  func presentMovie()
}

protocol MovieDetailInteractorInterface:class{
}
