//
//  MovieDetailPresenter.swift
//  movieApp
//
//  Created by Carlos Torres Sanchez on 7/1/19.
//  Copyright (c) 2019 Carlos Torres Sanchez. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MovieDetailPresenter {

    // MARK: - Private properties -

    private unowned let view: MovieDetailViewInterface
    private let interactor: MovieDetailInteractorInterface
    private let wireframe: MovieDetailWireframeInterface
    var movie:MovieResult?

    // MARK: - Lifecycle -

    init(view: MovieDetailViewInterface, interactor: MovieDetailInteractorInterface, wireframe: MovieDetailWireframeInterface) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension MovieDetailPresenter: MovieDetailPresenterInterface {
  func presentMovie() {
    view.presentMovieDetail(with: movie!)
    
  }
  
}
