//
//  MovieDetailInterfaces.swift
//  movieApp
//
//  Created by Carlos Torres Sanchez on 7/1/19.
//  Copyright (c) 2019 Carlos Torres Sanchez. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol MovieDetailWireframeInterface: WireframeInterface {
}

protocol MovieDetailViewInterface:class {
  func presentMovieDetail(with movie:MovieResult)
  func presentMovieCoverImage(Data:Data)

}

protocol MovieDetailPresenterInterface:class{
  
  func presentMovie()
  func presentMovieCoverImage(URL:URL)
}

protocol MovieDetailInteractorInterface:class{
  func presentMovieCoverImage(URL:URL)
}

protocol MovieDetailInteractorPresenterInterface:class{

  func presentMovieCoverImage(data:Data)
  
}

