//
//  MovieDetailInteractor.swift
//  movieApp
//
//  Created by Carlos Torres Sanchez on 7/1/19.
//  Copyright (c) 2019 Carlos Torres Sanchez. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MovieDetailInteractor {
}

// MARK: - Extensions -

extension MovieDetailInteractor: MovieDetailInteractorInterface {
}
